apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-backend
  template:
    metadata:
      labels:
        app: login-backend
    spec:
      containers:
      - name: login-backend
        image: bounajia/login:tagname
        env:
          - name: DB_HOST
            value: mysql
          - name: DB_PORT
            value: "4306"
          - name: DB_USERNAME
            value: your_db_username
          - name: DB_PASSWORD
            value: ""
          - name: DB_NAME
            value: login
            value: "8084"
        ports:
        - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  selector:
    app: login-backend
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
