apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-backend
  template:
    metadata:
      labels:
        app: login-backend
    spec:
      containers:
      - name: login-backend
        image: bounajia/login:tagname
        env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:mysql://mysql:4306/login?useSSL=false"
          - name: SPRING_DATASOURCE_USERNAME
            value: root
          - name: SPRING_DATASOURCE_PASSWORD
            value: ""
          - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
            value: org.hibernate.dialect.MySQLDialect
          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            value: update
          - name: SERVER_PORT
            value: "8084"
        ports:
        - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  selector:
    app: login-backend
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
