apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
      - name: search-container
        image: bounajia/search:tagname
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  selector:
    app: search
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
